name: ✨ Feature Request
description: Suggest an idea for this project
title: "✨ [Feature]: "
labels: ["feature", "pending-dev"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "Clearly describe the problem this feature aims to solve."
      placeholder: "Users are currently unable to..."
    validations:
      required: true

  - type: textarea
    id: expected-solution
    attributes:
      label: Expected Solution
      description: "Describe the solution you envision. How should this feature work from a user's perspective?"
      placeholder: "I expect to see a new button that, when clicked, performs X, Y, Z..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        List clear, measurable, and testable criteria that define when this feature is complete and working correctly.
        These criteria will be used by the AI TESTER to write tests and validate the implementation.
        Each criterion should be verifiable.
      placeholder: |
        - [ ] When a user performs X, the system should respond with Y.
        - [ ] The new component Z should display P data from Q source.
        - [ ] Error messages for invalid input A should be "Invalid input: Please provide B."
        - [ ] The performance of feature C should be less than D milliseconds.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."

  - type: textarea
    id: constraints
    attributes:
      label: Constraints / Non-Goals
      description: |
        Explicitly list what is OUT OF SCOPE.
        This prevents over-engineering and unwanted features.
      placeholder: |
        - No authentication
        - No persistence layer
        - No UI framework
        - Do not modify existing APIs
    validations:
      required: true
